### ISSUE TITLE
Hawkular panel gives error connection refused

### ISSUE THREAD

**Issue by thesteve0** [openshift-evangelists/vagrant-origin#10]
Going to https://hawkular-metrics.apps.10.2.2.2.xip.io/
gives connection refused. 

But if I open a terminal in a pod and go to 

sh-4.2$ curl -k https://172.30.94.192:443                                       
                                                                           
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">                 
<html>                                                                          
<head>                                                                          
  <meta http-equiv="refresh" content="0;hawkular/metrics">                      
  <title>Hawkular Metrics</title>       

So something is not working correctly with external routing. I am going to try to load the sample app and see if routing works for that as well.

**Comment by thesteve0** [comment]
Same errors happens when I create a new project with a new service and route. Looks like it is something wrong with the routing layer

**Comment by jorgemoralespou** [comment]
It seems there is a problem with the router probes. Opened an issue:

https://github.com/openshift/origin/issues/7308

**Comment by jorgemoralespou** [comment]
It looked like it does not support ipv6, so now I changed provisioning mode to disable ipv6 by default and different way of setting hostname. If base box shipped whitout ipv6 support hack would have not been necessary.
