### ISSUE TITLE
Please add a persistent Volume to the VM

### ISSUE THREAD

**Issue by thesteve0** [openshift-evangelists/vagrant-origin#14]
Can we please have one 5 gig NFS PV in the VM so developers can try using PVCs

**Comment by jorgemoralespou** [comment]
I've enabled NFS in the VM, added 10 mounts that can be used, and created 5 PVs by default with sizes ranging from 1Gi to 5Gi in ReadWriteOnly and ReadWriteMany adn Recycle policies.

Added a note at the bottom of README on how to use the remaining 5 mounts for new PVs.

**Comment by thesteve0** [comment]
You are awesome!
