### ISSUE TITLE
Hawkular and Heapster not functioning

### ISSUE THREAD

**Issue by jgammon612** [openshift-evangelists/vagrant-origin#29]
Hawkular shows: Crash loop back off
This was working while we are at OSCON so whatever new image was built seems to have broken the metrics

Error syncing pod, skipping: failed to "StartContainer" for "hawkular-metrics" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=hawkular-metrics pod=hawkular-metrics-eh0a3_openshift-infra(34abb13e-fde8-11e5-bee3-525400659b2e)"

Same for Heapster
Error syncing pod, skipping: failed to "StartContainer" for "heapster" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=heapster pod=heapster-e1rp3_openshift-infra(25ef9380-fde8-11e5-bee3-525400659b2e)"

**Comment by jorgemoralespou** [comment]
New release shipping today will fix the issue. 

# vagrant box update thesteve0/openshift-origin

**Comment by jgammon612** [comment]
Did a vagrant box update to 1.2 -- metrics still not working. Here is the error:
=================================================================
15:04:27,598 INFO  [org.cassalog.core.CassalogImpl] (metricsservice-lifecycle-thread) Executing [script:vfs:/content/hawkular-metrics-api-jaxrs.war/WEB-INF/lib/hawkular-metrics-schema-0.15.0.Final.jar/org/hawkular/schema/cassalog.groovy, tags:[0.15.x], vars:[keyspace:hawkular_metrics, reset:false, session:com.datastax.driver.core.SessionManager@3a4d2d4b]]
15:04:27,969 FATAL [org.hawkular.metrics.api.jaxrs.MetricsServiceLifecycle] (metricsservice-lifecycle-thread) HAWKMETRICS200006: An error occurred trying to connect to the Cassandra cluster: groovy.lang.MissingPropertyException: No such property: tables for class: org.cassalog.core.CassalogImpl
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
===========================================================================

Cassandra nodes are running though
INFO  14:59:58 Node hawkular-cassandra-1-14zjd/172.17.0.3 state jump to NORMAL
INFO  14:59:58 Waiting for gossip to settle before accepting client requests...
INFO  15:00:06 No gossip backlog; proceeding
INFO  15:00:07 Netty using native Epoll event loop
INFO  15:00:07 Enabling encrypted CQL connections between client and server
INFO  15:00:07 Using Netty Version: [netty-buffer=netty-buffer-4.0.23.Final.208198c, netty-codec=netty-codec-4.0.23.Final.208198c, netty-codec-http=netty-codec-http-4.0.23.Final.208198c, netty-codec-socks=netty-codec-socks-4.0.23.Final.208198c, netty-common=netty-common-4.0.23.Final.208198c, netty-handler=netty-handler-4.0.23.Final.208198c, netty-transport=netty-transport-4.0.23.Final.208198c, netty-transport-rxtx=netty-transport-rxtx-4.0.23.Final.208198c, netty-transport-sctp=netty-transport-sctp-4.0.23.Final.208198c, netty-transport-udt=netty-transport-udt-4.0.23.Final.208198c]
INFO  15:00:07 Starting listening for CQL clients on hawkular-cassandra-1-14zjd/172.17.0.3:9042...
INFO  15:00:07 Binding thrift service to hawkular-cassandra-1-14zjd/172.17.0.3:9160
INFO  15:00:07 enabling encrypted thrift connections between client and server
INFO 15:00:07 Listening for thrift clients...

**Comment by jgammon612** [comment]
vagrant box update will not fix the issue. Issue is fixed via a vagrant destroy and vagrant up -- moot since the version released is now functioning
