### ISSUE TITLE
Cockpit - Remove hard coded URL?

### ISSUE THREAD

**Issue by jfmatth** [openshift-evangelists/vagrant-origin#31]
Hi,

Is it possible to make the cockpit install more generic, and remove any hardcoded IP's or URL's?

I'm hoping to use what you've created and use it for my own install.

Thanks,

J

**Comment by jorgemoralespou** [comment]
@jfmatth what do you mean by making it more generic? What are you changing, using in your own install?

**Comment by jorgemoralespou** [comment]
I've done some changes, and updated 2 files in last commit. See if this is what you wanted or something else.

**Comment by jfmatth** [comment]
Jorge, thanks and checking now.  Looks to be about what I was meaning.

**Comment by jfmatth** [comment]
Yup, looks better, thank you Jorge.
