### ISSUE TITLE
Old docker version on centos

### ISSUE THREAD

**Issue by iconoeugen** [openshift-evangelists/vagrant-origin#35]
The latest `centos` images that are pushed on hub.docker.com require at least docker engine 1.10 that supports schema version 2:

```
Downloading "https://github.com/iconoeugen/docker-nginx.git" ...
Step 1 : FROM centos@sha256:7b754086d2c7d74ac39dc0a2545d7b06d4266f873d502feb5b3e8bfca27c5dd8
Trying to pull repository docker.io/library/centos ... failed
error: build error: unsupported schema version 2 for tag "sha256:7b754086d2c7d74ac39dc0a2545d7b06d4266f873d502feb5b3e8bfca27c5dd8"
```

**Comment by jfmatth** [comment]
The issue around docker 1.10 is for docker storage.  Typically you setup another volume that docker-storage-setup can utilize, and in Centos vagrant image, that's easy (add another disk, run docker-storage-setup, viola).  However, on other .BOX's that's not so easy.

Looks like loopback support is going away quickly in docker, unless i'm not seeing this right.

**Comment by dwmkerr** [comment]
For anyone who Google's their way here like I did, you can also try:


```bash
oc set env dc/docker-registry -n default REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ACCEPTSCHEMA2=true
systemctl restart origin-master.service
```

This manually enables the new schema version.

See: https://access.redhat.com/solutions/2391351
