### ISSUE TITLE
4096 Memory may not be enough

### ISSUE THREAD

**Issue by jfmatth** [openshift-evangelists/vagrant-origin#37]
I'm starting to see the provisioning of the VM failing with 'can't allocate memory' for gcc and GO.

I'm doing more testing, but i think the minimum may be getting closer to 6gb for building the VM, but then when it's run, 4gb should work.

Is anyone else seeing this?

BTW, i'm starting to test with Fedora 24 cloud base.

**Comment by jorgemoralespou** [comment]
I`ll bump default memory to 6GB as you suggest. To be honest, I have mem overrided in my local env to 8GB so probably I would never had noticed.

Thanks John.
