### ISSUE TITLE
libvirt image availability

### ISSUE THREAD

**Issue by ryanj** [openshift-evangelists/vagrant-origin#6]
@maxamillion requested that we make a libvirt image available on Atlas as well.

**Comment by jorgemoralespou** [comment]
@ryanj once we have the process that @thesteve0 is using to package the boxes, maybe we can follow the same to create a libvirt box and publish it into atlas. Let's discuss this in Brno.

**Comment by thesteve0** [comment]
@ryanj  this repo makes it possible for someone to build the libvirt image themselves if they want. I have little interest in building the libvirt image but someone else can build it.  I would like to keep making the virtualbox image the best it can be. I will also update the scripts that I use to make the virtualbox and then let libvirt people do the same steps to package up theres. If someone wants to make one I can upload it to atlas or I can point to their upload on the /vm page
