### ISSUE TITLE
Need updated Docs

### ISSUE THREAD

**Issue by ryanj** [openshift-evangelists/vagrant-origin#7]
The usage Docs are out of date

**Comment by jorgemoralespou** [comment]
@thesteve0 if I understand @ryanj request, this is for the openshift.org/vm Doc. Maybe the doc could be hosted here in asciidoc, and we could create a pdf out of it. That way we can maintain that document together with the image. WDYT?

**Comment by thesteve0** [comment]
see the other bug, please move to openshift.org repo and assign to me
