### ISSUE TITLE
no mention of 10.2.2.2 on the /vm page

### ISSUE THREAD

**Issue by ryanj** [openshift-evangelists/vagrant-origin#8]
need information on how to connect to the cluster after it's booted.

**Comment by jorgemoralespou** [comment]
Steve, If I understand correctly @ryanj request, he's talking about openshift.org/vm, which is under your responsibility.

**Comment by thesteve0** [comment]
yup he is. Ryan, please move all /vm bugs to openshift.org and assign to me
